export const FAIL_MEMBER = "FAIL_MEMBER";
export const GET_MEMBER = "GET_MEMBER";
export const GET_MEMBERS = "GET_MEMBERS";
export const LOAD_MEMBER = "LOAD_MEMBER";
export const LOGIN_MEMBER = "LOGIN_MEMBER";
export const REGISTER_MEMBER = "REGISTER_MEMBER";
export const CURRENT_MEMBER = "CURRENT_MEMBER";
export const LOGOUT_MEMBER = "LOGOUT_MEMBER";
